"""
Perseus Vault x AMD Instinct — live interactive demo.

A tiny Flask app that wraps the SAME CPU-only engine the repo ships
(src/perseus_vault_store.ReferenceStore: SQLite + FTS5 hybrid recall) so a visitor
can, in their browser:

  1. Teach an agent durable facts (Session 1).
  2. Open a brand-new session (context cleared) and recall them (Session 2) —
     proving memory survives the context window.
  3. Run a decay tick and watch noise get archived while signal stays.

Everything here runs on the host CPU — 0 bytes of GPU HBM — which is the whole AMD
economics argument. The cost table shown alongside is now MEASURED on real rented
hardware (one MI300X + one 2x H100 pair, Qwen2.5-72B via vLLM — docs/BENCHMARKS.md
§3a/§3b/§3c/§3d) — every cross-vendor row is measured, no projection remains.

Guardrails for a public demo: each visitor gets an isolated in-memory store keyed by
a cookie; stores are capped, rate-limited, and auto-evicted when idle.
"""

from __future__ import annotations

import os
import sys
import time
import threading
import uuid

from flask import Flask, jsonify, request, make_response

# Reuse the repo's real engine + economics (mounted at /app/src in the container).
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, "/app/src")
from perseus_vault_store import ReferenceStore  # noqa: E402
import economics  # noqa: E402

app = Flask(__name__)

# --- per-visitor sandbox ----------------------------------------------------
_LOCK = threading.Lock()
_SESSIONS: dict[str, dict] = {}          # sid -> {store, last, count, hits[]}
IDLE_TTL_SEC = 20 * 60
MAX_SESSIONS = 300
MAX_MEMORIES_PER_SID = 500
MAX_TEXT = 500
MAX_QUERY = 200
RATE_MAX = 60                            # requests / RATE_WINDOW / sid
RATE_WINDOW = 60.0


def _reap(now: float) -> None:
    dead = [s for s, v in _SESSIONS.items() if now - v["last"] > IDLE_TTL_SEC]
    for s in dead:
        try:
            _SESSIONS[s]["store"].close()
        except Exception:
            pass
        _SESSIONS.pop(s, None)
    while len(_SESSIONS) > MAX_SESSIONS:
        oldest = min(_SESSIONS, key=lambda s: _SESSIONS[s]["last"])
        try:
            _SESSIONS[oldest]["store"].close()
        except Exception:
            pass
        _SESSIONS.pop(oldest, None)


def _session(sid: str) -> dict:
    now = time.time()
    _reap(now)
    v = _SESSIONS.get(sid)
    if v is None:
        v = {"store": ReferenceStore(":memory:"), "last": now,
             "reqs": [], "seeded": False}
        _SESSIONS[sid] = v
    v["last"] = now
    return v


def _rate_ok(v: dict, now: float) -> bool:
    v["reqs"] = [t for t in v["reqs"] if now - t < RATE_WINDOW]
    if len(v["reqs"]) >= RATE_MAX:
        return False
    v["reqs"].append(now)
    return True


def _sid_from(req) -> str:
    return req.cookies.get("pv_sid") or uuid.uuid4().hex


def _hit_json(h) -> dict:
    return {
        "text": h.memory.text,
        "category": h.memory.category,
        "recall_count": h.memory.recall_count,
        "rank": round(h.rank, 3),
    }


# --- live inference (Fireworks AI API), budget-guarded -----------------------
# The memory layer above is CPU-only. The agent's ANSWER is generated by an
# open-weight LLM via the Fireworks AI API — the hackathon's designated inference
# partner. No serving API attests which accelerator handles a request, so we never
# label an answer with specific hardware. Because this is a public endpoint spending
# a shared credit balance, calls are hard-capped per day and in total; when the cap
# is hit (or no key is set) we fall back to a labelled memory-grounded composition
# and never fabricate an LLM answer.
FIREWORKS_API_KEY = os.environ.get("FIREWORKS_API_KEY", "")
FIREWORKS_MODEL = os.environ.get("FIREWORKS_MODEL",
                                 "accounts/fireworks/models/gpt-oss-120b")
FW_MAX_TOKENS = int(os.environ.get("FW_MAX_TOKENS", "160"))
FW_DAILY_CALLS = int(os.environ.get("FW_DAILY_CALLS", "5000"))
FW_TOTAL_CALLS = int(os.environ.get("FW_TOTAL_CALLS", "40000"))
_BUDGET = {"day": "", "calls": 0, "total": 0}
_BUDGET_LOCK = threading.Lock()


def _budget_ok() -> bool:
    today = time.strftime("%Y-%m-%d", time.gmtime())
    with _BUDGET_LOCK:
        if _BUDGET["day"] != today:
            _BUDGET["day"], _BUDGET["calls"] = today, 0
        if _BUDGET["total"] >= FW_TOTAL_CALLS or _BUDGET["calls"] >= FW_DAILY_CALLS:
            return False
        _BUDGET["calls"] += 1
        _BUDGET["total"] += 1
        return True


def infer(query: str, grounding: str):
    """Return (answer, backend_label, used_llm). Real LLM via Fireworks when keyed and
    under budget; otherwise an honest, accurately-labelled memory-grounded composition."""
    if not FIREWORKS_API_KEY:
        why = "no inference key configured on this deployment"
    elif not grounding:
        why = "nothing recalled yet to ground an answer"
    elif not _budget_ok():
        why = "the demo's daily inference budget is reached"
    else:
        import json as _json
        import urllib.request as _u
        prompt = (f"Using ONLY these remembered facts:\n{grounding}\n\n"
                  f"Answer in one or two sentences: {query}")
        body = _json.dumps({
            "model": FIREWORKS_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": FW_MAX_TOKENS, "temperature": 0.3,
        }).encode()
        try:
            req = _u.Request(
                "https://api.fireworks.ai/inference/v1/chat/completions",
                data=body, headers={"Authorization": f"Bearer {FIREWORKS_API_KEY}",
                                    "Content-Type": "application/json"})
            with _u.urlopen(req, timeout=30) as r:
                d = _json.loads(r.read())
            text = (d["choices"][0]["message"].get("content") or "").strip()
            if text:
                short = FIREWORKS_MODEL.split("/")[-1]
                return text, f"{short} via Fireworks AI (live)", True
        except Exception:
            pass                                   # fall through to composition
        why = "the inference call failed"
    facts = [ln[2:] for ln in grounding.splitlines() if ln.startswith("- ")]
    if facts:
        text = "Grounded in memory: " + " ".join(facts[:2])
    else:
        text = "I have no memory matching that yet - teach me a fact first."
    return text, f"memory-grounded composition (live inference paused: {why})", False


# --- API --------------------------------------------------------------------
@app.route("/api/remember", methods=["POST"])
def api_remember():
    sid = _sid_from(request)
    data = request.get_json(silent=True) or {}
    text = (data.get("text") or "").strip()[:MAX_TEXT]
    category = (data.get("category") or "fact").strip()[:60] or "fact"
    if not text:
        return _resp(sid, {"error": "empty text"}, 400)
    with _LOCK:
        v = _session(sid)
        if not _rate_ok(v, time.time()):
            return _resp(sid, {"error": "rate limited — slow down"}, 429)
        if v["store"].count(include_archived=True) >= MAX_MEMORIES_PER_SID:
            return _resp(sid, {"error": "demo store full — hit Reset"}, 409)
        v["store"].remember(category, text)
        v["store"].db.commit()
        active = v["store"].count()
    return _resp(sid, {"ok": True, "active": active})


@app.route("/api/recall", methods=["POST"])
def api_recall():
    sid = _sid_from(request)
    data = request.get_json(silent=True) or {}
    query = (data.get("query") or "").strip()[:MAX_QUERY]
    if not query:
        return _resp(sid, {"error": "empty query"}, 400)
    with _LOCK:
        v = _session(sid)
        if not _rate_ok(v, time.time()):
            return _resp(sid, {"error": "rate limited — slow down"}, 429)
        hits = [_hit_json(h) for h in v["store"].recall(query, k=5)]
        active = v["store"].count()
    # Recall (CPU) is done; generate the answer on AMD Instinct outside the lock.
    grounding = "\n".join(f"- {h['text']}" for h in hits)
    answer, backend, used_llm = infer(query, grounding)
    return _resp(sid, {"ok": True, "hits": hits, "active": active,
                       "answer": answer, "backend": backend, "used_llm": used_llm})


@app.route("/api/decay", methods=["POST"])
def api_decay():
    sid = _sid_from(request)
    with _LOCK:
        v = _session(sid)
        if not _rate_ok(v, time.time()):
            return _resp(sid, {"error": "rate limited — slow down"}, 429)
        # Simulate the passage of ~90 idle days so the decay tick has visible effect
        # in a live demo (real deployments run this on a schedule over real time).
        archived = v["store"].decay(now=time.time() + 90 * 86400)
        active = v["store"].count()
        total = v["store"].count(include_archived=True)
    return _resp(sid, {"ok": True, "archived": archived,
                       "active": active, "archived_total": total - active})


@app.route("/api/reset", methods=["POST"])
def api_reset():
    sid = _sid_from(request)
    with _LOCK:
        old = _SESSIONS.pop(sid, None)
        if old:
            try:
                old["store"].close()
            except Exception:
                pass
        _session(sid)
    return _resp(sid, {"ok": True, "active": 0})


@app.route("/api/economics")
def api_economics():
    rows = list(economics.economics_rows())
    return jsonify({
        "model": economics.MEASURED_MODEL_NAME,
        "weights_gb": economics.MEASURED_WEIGHTS_GB,
        "kv_gb_per_seq": round(economics.KV_GB_PER_SEQ, 2),
        "pv_rss_mb_per_agent": economics.PV_RSS_MB_PER_AGENT,
        "pv_usd_per_agent_hr": round(economics.perseus_vault_cost_per_agent_hr(), 5),
        "rows": rows,
        "data_source": "measured",
    })


@app.route("/healthz")
def healthz():
    return jsonify({"ok": True, "sessions": len(_SESSIONS)})


def _resp(sid: str, payload: dict, status: int = 200):
    resp = make_response(jsonify(payload), status)
    resp.set_cookie("pv_sid", sid, max_age=IDLE_TTL_SEC, samesite="Lax",
                    secure=True, httponly=True)
    return resp


@app.route("/")
def index():
    return INDEX_HTML


INDEX_HTML = r"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Perseus Vault × AMD Instinct — live demo</title>
<style>
  :root{--bg:#0c0f14;--panel:#141a22;--edge:#232c38;--ink:#e6edf3;--mut:#8aa0b4;
        --grn:#41d18a;--gold:#ffc230;--blue:#5aa9ff;--red:#ff6b6b}
  *{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--ink);
    font:15px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
  a{color:var(--blue)} .wrap{max-width:1080px;margin:0 auto;padding:26px 18px 60px}
  h1{font-size:24px;margin:0 0 2px} .sub{color:var(--mut);margin:0 0 16px}
  .banner{border:1px solid var(--gold);border-radius:8px;padding:10px 14px;margin:14px 0;
    color:var(--gold);background:rgba(255,194,48,.06);font-size:13px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  @media(max-width:820px){.grid{grid-template-columns:1fr}}
  .card{background:var(--panel);border:1px solid var(--edge);border-radius:10px;padding:16px}
  .card h2{font-size:15px;margin:0 0 4px} .step{color:var(--blue);font-weight:700}
  .hint{color:var(--mut);font-size:12.5px;margin:0 0 10px}
  input,button{font:inherit} input[type=text]{width:100%;background:#0a0d12;color:var(--ink);
    border:1px solid var(--edge);border-radius:7px;padding:9px 11px}
  .row{display:flex;gap:8px;margin-top:8px} .row input{flex:1}
  button{background:#1b2430;color:var(--ink);border:1px solid var(--edge);border-radius:7px;
    padding:9px 13px;cursor:pointer} button:hover{border-color:var(--blue)}
  button.go{background:var(--blue);color:#04121f;border-color:var(--blue);font-weight:700}
  .chips{display:flex;flex-wrap:wrap;gap:6px;margin:2px 0 4px}
  .chip{font-size:12px;padding:5px 9px;border:1px dashed var(--edge);border-radius:20px;
    color:var(--mut);cursor:pointer} .chip:hover{color:var(--ink);border-color:var(--blue)}
  .log{background:#0a0d12;border:1px solid var(--edge);border-radius:7px;padding:10px;
    margin-top:10px;min-height:34px;font-size:13px;white-space:pre-wrap}
  .hit{border-left:3px solid var(--grn);padding:6px 10px;margin:7px 0;background:#0a0d12;border-radius:4px}
  .hit .m{color:var(--mut);font-size:12px} .ok{color:var(--grn)} .warn{color:var(--red)}
  table{border-collapse:collapse;width:100%;font-size:12.5px;margin-top:6px}
  th,td{border-bottom:1px solid var(--edge);padding:6px 8px;text-align:right}
  th:first-child,td:first-child{text-align:left} tr.mi td{color:var(--grn)}
  .pill{display:inline-block;font-size:11px;padding:2px 7px;border-radius:20px;
    border:1px solid var(--edge);color:var(--mut)} .gpu0{color:var(--grn);border-color:var(--grn)}
  .foot{color:var(--mut);font-size:12px;margin-top:22px;border-top:1px solid var(--edge);padding-top:12px}
  .stat{color:var(--mut);font-size:12px;margin-top:8px}
  .ans{margin-top:10px;padding:9px 11px;border-left:3px solid var(--blue);
    background:#0a0d12;border-radius:4px} .ans .bk{color:var(--mut);font-size:11px}
</style></head><body><div class="wrap">
  <h1>Perseus Vault <span style="color:var(--mut)">×</span> AMD Instinct MI300X</h1>
  <p class="sub">Encrypted, local-first agent memory — kept <b>off the GPU</b>. Recall runs on the
     <b>host CPU</b>; the agent's answer is generated live by an open-weight LLM via the
     <b>Fireworks AI API</b>.<br>
     <b>Judges:</b> tap an example below to teach a fact, then hit <b>Recall</b> — and read the
     live LLM answer grounded only in what was recalled.</p>

  <div class="banner">⚠︎ Honesty: recall &amp; footprint are <b>measured live on this CPU</b>
     (<span class="gpu0">0 bytes of GPU HBM</span>). The agent's <b>answer</b> is generated live by
     an open-weight LLM via <b>Fireworks AI</b> — the hackathon's inference partner, now
     <a href="https://fireworks.ai/blog/fireworks-amd-ai-infrastructure-partnership">partnering with
     AMD</a> to serve on Instinct; no serving API attests which accelerator handles a request, so we
     don't claim one. (Daily budget cap; falls back to a labelled memory-grounded composition.) The
     cost table below is <b>measured</b> on real rented hardware — one MI300X and one 2×H100 pair
     2× A100 80GB, and 8× A100 40GB (Qwen2.5-72B, vLLM) — every row measured, no projection.</div>

  <div class="grid">
    <div class="card">
      <h2><span class="step">Session 1</span> · teach the agent</h2>
      <p class="hint">Store durable facts. Tap an example or type your own.</p>
      <div class="chips" id="chips"></div>
      <div class="row"><input id="mem" type="text" placeholder="e.g. Deploy target is us-east-1 on MI300X"
        maxlength="500"><button class="go" onclick="remember()">Remember</button></div>
      <div class="stat" id="stat">active memories: 0</div>
      <div class="log" id="log1">nothing stored yet.</div>
    </div>

    <div class="card">
      <h2><span class="step">Session 2</span> · new session, recall</h2>
      <p class="hint"><button onclick="newSession()">↻ Start new session</button>
         clears the on-screen context — the vault persists. Then recall.</p>
      <div class="row"><input id="q" type="text" placeholder="e.g. where do we deploy?"
        maxlength="200"><button class="go" onclick="recall()">Recall</button></div>
      <div class="log" id="log2">start a new session, then ask something you taught.</div>
      <div style="margin-top:10px"><button onclick="decay()">Run decay tick (age ~90d)</button>
         <button onclick="reset()">Reset demo</button></div>
      <div class="log" id="log3"></div>
    </div>
  </div>

  <div class="card" style="margin-top:16px">
    <h2>Why AMD: one card, many agents <span class="pill gpu0">measured · MI300X + 2×A100 + 2×H100 + 8×A100</span></h2>
    <p class="hint" id="econhint">serving one 72B model; memory stays on CPU (0 HBM).</p>
    <table id="econ"><thead><tr><th>Accelerator</th><th>HBM</th><th>Cards</th>
      <th>Agents</th><th>$/GPU-hr</th><th>$/agent-hr</th><th>source</th></tr></thead><tbody></tbody></table>
    <p class="stat" id="pvcost"></p>
    <p class="stat"><b class="ok">11.7× cheaper per agent-hour than 2×H100 — measured, not projected.</b>
       A single H100 can't load the model at all; the MI300X holds it on one card with KV headroom to spare.</p>
  </div>

  <p class="foot">Same recall design as the shipping product (CPU reference implementation):
     <a href="https://github.com/Perseus-Computing-LLC/perseus-vault">perseus-vault</a> ·
     submission repo <a href="https://github.com/tcconnally/perseus-amd-act-ii">perseus-amd-act-ii</a> ·
     <a href="https://github.com/tcconnally/perseus-amd-act-ii/blob/main/demo_video.mp4">video</a> · MIT.
     Per-visitor sandbox, auto-resets when idle.</p>
</div>
<script>
const EX=["Our deploy target is AWS us-east-1 on an MI300X.",
 "The on-call rotation lead this week is Dana.",
 "Perseus Vault keeps memory on the CPU, not the GPU.",
 "Postgres is banned in this project; we use SQLite + FTS5.",
 "The MI300X has 192 GB of HBM3."];
const chips=document.getElementById('chips');
EX.forEach(t=>{const c=document.createElement('span');c.className='chip';c.textContent=t;
  c.onclick=()=>{document.getElementById('mem').value=t;remember();};chips.appendChild(c);});
async function post(u,b){const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},
  body:JSON.stringify(b||{})});return r.json();}
function setStat(n){document.getElementById('stat').textContent='active memories: '+n;}
async function remember(){const el=document.getElementById('mem');const t=el.value.trim();if(!t)return;
  const d=await post('/api/remember',{text:t});const l=document.getElementById('log1');
  if(d.error){l.innerHTML='<span class="warn">'+d.error+'</span>';return;}
  setStat(d.active);el.value='';l.innerHTML='<span class="ok">stored ✓</span>  "'+t+'"';}
function newSession(){document.getElementById('log2').innerHTML=
  '<span class="ok">— new session —</span> context cleared. The vault still holds your facts. Now recall:';}
async function recall(){const q=document.getElementById('q').value.trim();if(!q)return;
  const d=await post('/api/recall',{query:q});const l=document.getElementById('log2');
  if(d.error){l.innerHTML='<span class="warn">'+d.error+'</span>';return;}
  if(!d.hits.length){l.innerHTML='no matching memory. Teach it in Session 1 first.';return;}
  l.innerHTML='<span class="ok">recalled from the vault ('+d.active+' active):</span>'+
   d.hits.map(h=>'<div class="hit">'+esc(h.text)+'<div class="m">['+esc(h.category)+'] recalls='+
   h.recall_count+' · fused rank '+h.rank+'</div></div>').join('')+
   (d.answer?'<div class="ans"><b>agent answer</b> <span class="bk">'+esc(d.backend)+
   '</span><br>'+esc(d.answer)+'</div>':'');}
function esc(s){return (s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
async function decay(){const d=await post('/api/decay',{});const l=document.getElementById('log3');
  if(d.error){l.innerHTML='<span class="warn">'+d.error+'</span>';return;}
  l.innerHTML='<span class="ok">decay tick:</span> archived '+d.archived+
   ' faded memories; '+d.active+' kept active (nothing deleted — archive is auditable).';setStat(d.active);}
async function reset(){await post('/api/reset',{});setStat(0);
  document.getElementById('log1').textContent='nothing stored yet.';
  document.getElementById('log2').textContent='start a new session, then ask something you taught.';
  document.getElementById('log3').textContent='';}
(async()=>{const e=await (await fetch('/api/economics')).json();
  document.getElementById('econhint').textContent='serving '+e.model+
   ' — weights '+e.weights_gb+' GB, KV '+e.kv_gb_per_seq+' GB/seq; memory on CPU (0 HBM).';
  const tb=document.querySelector('#econ tbody');
  e.rows.forEach(r=>{const tr=document.createElement('tr');if(r.gpu.includes('MI300X'))tr.className='mi';
    const agents=r.concurrent_agents!=null?r.concurrent_agents.toFixed(1):'<span class="warn">cannot load</span>';
    const perag=r.gpu_usd_per_agent_hr!=null?'$'+r.gpu_usd_per_agent_hr:'—';
    const src='<span class="pill'+(r.data_source=='measured'?' gpu0':'')+'">'+r.data_source+'</span>';
    tr.innerHTML='<td>'+r.gpu+'</td><td>'+r.hbm_gb+' GB</td><td>'+r.cards_for_weights+
     '</td><td>'+agents+'</td><td>$'+r.gpu_usd_per_hr+'</td><td>'+perag+'</td><td>'+src+'</td>';
    tb.appendChild(tr);});
  document.getElementById('pvcost').textContent='Perseus Vault memory: ~$'+e.pv_usd_per_agent_hr+
   '/agent-hr on the host CPU ('+e.pv_rss_mb_per_agent+' MB RSS/agent, 0 bytes HBM) — measured footprint.';})();
</script></body></html>"""


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "8080")))
